naver/egjs-view360

- test/unit/SpinViewer/SpriteImage.spec.js
> test(SpriteImage): skip test which is dependent on network env.

- test/unit/SpinViewer/SpriteImage.spec.js
> test(SpriteImage): skip remote image test

- test/unit/SpinViewer/SpinViewer.spec.js
> test(SpinViewer): skip remote image test for CI

- src/YawPitchControl/YawPitchControl.js
- src/YawPitchControl/input/DeviceMotion.js
- src/YawPitchControl/input/FusionPoseSensor.js
- test/unit/YawPitchControl/DeviceMotion.spec.js
- test/unit/YawPitchControl/MoveKeyInput.spec.js
> fix(PanoViewer): migration for egjs-component 2.1.0

- demo/_layouts/main.html
>  docs(all): fix wrong github link

- README.md
> docs(README): update link for view360 subpage.

- README.md
#10
Change thumb image url and size.
> docs(README): update thumb images.

- src/YawPitchControl/YawPitchControl.js
- test/unit/YawPitchControl/FusionPoseSensor.spec.js
- test/unit/YawPitchControl/YawPitchControl.spec.js
#35 
* un skipped unit test for YawPitchControl
> test(YawPitchControl): add/unskip unit test

- README.md
- package.json
- test/unit/YawPitchControl/YawPitchControl.spec.js
Ref #49 
Axes 2.3.0 fixs bugs related with circular.
> Apply axes 2.3.0

- demo/assets/html/panoviewer.html
- demo/assets/html/spinviewer.html
- package-lock.json
> docs(view360): enhance demo

- test/manual/PanoViewer/ContextLost.html
- test/manual/PanoViewer/Events.html
- test/manual/PanoViewer/PanoVideo.html
Ref #184 
PanoVideo.html(manual test for playing video) is still following 2.x interface. It need to apply changed interaface of 3.0
> test(PanoVideo): apply changed interface.

- package.json
- src/PanoImageRenderer/WebGLUtils.js
- src/PanoImageRenderer/renderer/CubeRenderer.js
- src/PanoImageRenderer/renderer/SphereRenderer.js
- test/unit/PanoImageRenderer/WebGLUtils.spec.js
#197
Although there's webgl exception. it should ignore exception.
> refactor(WebGLUtils): ignore webgl exception.

- src/YawPitchControl/YawPitchControl.js
- test/unit/PanoViewer/PanoViewer.spec.js
- test/unit/YawPitchControl/YawPitchControl.spec.js
> fix(YawPitchControl): lookAt allow duration to be more than 1s

- src/PanoViewer/index.js
- src/SpinViewer/index.js
- test/unit/PanoImageRenderer/PanoImageRenderer.spec.js
> chore(all): Add jsdoc for VERSION

- src/utils/browserFeature.js
> chore(browserFeature): replace global with window

- .travis.yml
- declaration/PanoViewer.d.ts
- declaration/SpinViewer.d.ts
- declaration/index.d.ts
- package.json
- src/SpinViewer/SpinViewer.js
- test/unit/PanoImageRenderer/PanoImageRenderer.spec.js
> chore(all): Add type definition to support TypeScript

- karma.conf.js
- package-lock.json
- package.json
Do not use polyfill to support await / async
Ref #235
> chore(all): set babel setting to chrome 55

- test/unit/PanoImageRenderer/PanoImageRenderer.spec.js
- test/unit/util.js
Ref #237
It's only reproduce on CI environment.
I cannot reproduce in Ubuntu 14 Chrome Headless setting.
> test(PanoViewer): video test failure test on CI

- src/PanoViewer/PanoViewer.js
- test/unit/PanoImageRenderer/WebGLUtils.spec.js
- test/unit/PanoViewer/PanoViewer.spec.js
Ref #243
isWebGLAvailable should return true if PanoViewer is avilable.
> chore(PanoViewer): isWebGLAvailable spec change

- test/manual/PanoViewer/Panorama.html
- test/manual/css/panoviewer-control.css
- test/manual/lib/PieView.js
- test/manual/lib/screenfull.js
- test/manual/lib/util.js
> test(PanoViewer): enhance panorama test to be able to use local file.

- demo/common/css/PanoControls.css
- demo/common/css/example.css
- demo/common/js/GyroTouchOptions.js
- demo/common/js/PanoControls.js
- demo/examples/panoviewer/device-motion/motion-touch.html
- demo/examples/panoviewer/projection-type/index.html
- test/unit/util.js
> chore(demo): add gyro/touch demo

- demo/common/js/codepen.js
- demo/examples/panoviewer/etc/videojs.html
> chore(demo): add videojs demo

- demo/_includes/panoviewer/panoviewer_features.md
- demo/common/css/demo.css
- demo/examples/panoviewer/controls/keyboard-wheel.html
- demo/examples/panoviewer/etc/loading_indicator.html
- demo/examples/panoviewer/etc/partial_panorama.html
- demo/examples/panoviewer/etc/synchronize.html
- demo/examples/panoviewer/projection-type/cubemap_video.html
- demo/examples/panoviewer/projection-type/equirectangular_video.html
- demo/examples/panoviewer/projection-type/panorama_image.html
- demo/examples/panoviewer/projection-type/stereoequi.html
- demo/examples/panoviewer/projection-type/youtube.html
> chore(demo): demo update

- demo/common/css/demo.css
- demo/examples/panoviewer/controls/change_direction.html
- demo/examples/panoviewer/controls/custom-control.html
- demo/examples/panoviewer/controls/doc-embeded.html
- demo/examples/panoviewer/controls/keyboard-wheel.html
- demo/examples/panoviewer/controls/motion-touch.html
- demo/examples/panoviewer/controls/setting_initial_view.html
- demo/examples/panoviewer/etc/hotspot.html
- demo/examples/panoviewer/etc/loading_indicator.html
- demo/examples/panoviewer/etc/partial_panorama.html
- demo/examples/panoviewer/etc/responsive.html
- demo/examples/panoviewer/etc/synchronize.html
- demo/examples/panoviewer/etc/videojs.html
- demo/examples/panoviewer/projection-type/cubemap_image.html
- demo/examples/panoviewer/projection-type/cubemap_video.html
- demo/examples/panoviewer/projection-type/cubestrip_3x2_image.html
- demo/examples/panoviewer/projection-type/equirectangular_image.html
- demo/examples/panoviewer/projection-type/equirectangular_video.html
- demo/examples/panoviewer/projection-type/equirectangular_video_url.html
- demo/examples/panoviewer/projection-type/panorama_image.html
- demo/examples/panoviewer/projection-type/stereoequi.html
- demo/examples/panoviewer/projection-type/verticalcubestrip_image.html
- demo/examples/panoviewer/projection-type/youtube.html
- package-lock.json
> chore(demo): add home link to all demo

- demo/common/js/codepen.js
- demo/examples/panoviewer/etc/loading_indicator.html
The ```prev(../)``` relative address is incorrect in codepen.
> chore(demo): fix codepen js

- src/PanoViewer/PanoViewer.js
- src/utils/browser.js
- test/unit/PanoViewer/PanoViewer.spec.js
> fix(PanoViewer): fix delayed frame is not render

- src/YawPitchControl/YawPitchControl.js
- test/unit/PanoImageRenderer/PanoImageRenderer.spec.js
- test/unit/PanoViewer/PanoViewer.spec.js
- test/unit/YawPitchControl/YawPitchControl.spec.js
- test/unit/util.js
- update yaw range by fov change #290
- video test failure #292
> fix(YawPitchControl): update yaw range by fov change & video test failure

- .editorconfig
- declaration/PanoViewer.d.ts
- declaration/SpinViewer.d.ts
- demo/common/css/PanoControls.css
- demo/common/js/PanoControls.js
- src/PanoImageRenderer/PanoImageRenderer.js
- src/PanoViewer/PanoViewer.js
- src/PanoViewer/consts.js
- src/YawPitchControl/YawPitchControl.js
- src/YawPitchControl/input/DeviceSensorInput.js
- src/utils/browser.js
- src/utils/browserFeature.js
- test/manual/PanoViewer/VR.html
- test/unit/PanoImageRenderer/PanoImageRenderer.spec.js
- test/unit/YawPitchControl/DeviceSensorInput.spec.js
- test/unit/YawPitchControl/YawPitchControl.spec.js
- test/unit/utils/math-util.spec.js
#297 
Added "enter VR" button to previous demos.
I've also fixed the issue that animation not works while I'm working on it.
> feat: add VR controls to demo

- src/PanoImageRenderer/PanoImageRenderer.js
- This PR makes the shader program to cache the internal `uEye` uniform location.
> feat: cache eye index uniform

- declaration/PanoViewer.d.ts
- declaration/SpinViewer.d.ts
- package-lock.json
- package.json
- test/unit/PanoImageRenderer/CylinderRenderer.spec.js
- tslint.json
This fixes the declaration file's lint issue.
related: #317 
This will temporarily disable one test at CylinderRenderer.
#317 should be fixed to re-enable it.
> fix: typescript declarations

- .travis.yml
- package-lock.json
- package.json
- src/PanoImageRenderer/WebGLUtils.js
- src/PanoImageRenderer/renderer/CubeRenderer.js
- src/PanoImageRenderer/renderer/Renderer.js
- src/utils/browser.js
- test/unit/PanoImageRenderer/CubeRenderer.spec.js
- test/unit/PanoImageRenderer/PanoImageRenderer.spec.js
- test/unit/PanoImageRenderer/WebGLUtils.spec.js
- test/unit/PanoViewer/PanoViewer.spec.js
https://github.com/naver/egjs-agent/issues/33
> fix: update @egjs/agent

- package-lock.json
- package.json
- src/YawPitchControl/input/FusionPoseSensor.js
> fix: wrong devicemotion handling on iPad

- declaration/PanoViewer.d.ts
- src/PanoImageRenderer/PanoImageRenderer.js
- src/PanoImageRenderer/vr/XRManager.js
- src/PanoViewer/PanoViewer.js
- src/utils/utils.js
- test/unit/SpinViewer/SpinViewer.spec.js
> feat: add xrsessioninit options for XRManager

- package-lock.json
- src/PanoImageRenderer/PanoImageRenderer.ts
- test/unit/PanoImageRenderer/PanoImageRenderer.spec.js
> fix: video is not playable because of keepUpdate value

- src/PanoImageRenderer/PanoImageRenderer.ts
- src/PanoImageRenderer/renderer/CylinderRenderer.ts
- test/unit/YawPitchControl/ScreenRotationAngle.spec.js
None
Just replaced the word 'intialize' with 'initialize' in some comments & logs
> docs: fix typo

- src/PanoImageRenderer/vr/XRManager.ts
- src/PanoViewer/PanoViewer.ts
- src/YawPitchControl/YawPitchControl.ts
- src/types/event.ts
- test/manual/PanoViewer/PanoViewer.html
- test/unit/PanoImageRenderer/PanoImageRenderer.spec.js
- test/unit/PanoImageRendererForUnitTest.js
- test/unit/PanoViewer/PanoViewer.spec.js
- test/unit/YawPitchControl/YawPitchControl.spec.js
- test/unit/util.js
> fix: viewChange is not triggered

- src/PanoViewer/PanoViewer.ts
This fixes wrong cubemap config type definition
> fix: wrong cubemap type definition

- demo/examples/panoviewer/etc/videojs.html
- package-lock.json
- package.json
> docs: fix videojs demo not working on iOS

- package-lock.json
- package.json
- src/YawPitchControl/input/RotationPanInput.ts
- src/YawPitchControl/input/TiltMotionInput.ts
- test/unit/YawPitchControl/RotationPanInput.spec.js
This updates @egjs/axes used by view360 to the latest 3.3.0 version.
> chore: update @egjs/axes to 3.3.0

- package.json
This updates the version of the @egjs/axes to fix some axes versions not working in the IE browser.
> fix: update axes version

- packages/vue3-view360/package.json
- packages/vue3-view360/src/SpinViewer.ts
> fix: spinviewer prop is ignored

- packages/svelte-view360/build.js
- packages/svelte-view360/replace.cjs.js
> fix: replace in svelte build result
